from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from store.image_processing import optimise_uploaded_image
from store.models import CategoryImage


DEFAULT_CATEGORY_IMAGE = "category_images/default.png"

GENERATED_PREFIXES = (
    "category-header-",
    "category-thumbnail-",
)


def format_bytes(byte_count):
    """Return a human-readable byte count for command output."""
    if byte_count is None:
        return "unknown"

    value = float(byte_count)

    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.1f} {unit}"

        value /= 1024

    return f"{value:.1f} GB"


def is_generated_image(image_name):
    """
    Return True when the image was generated by the current optimiser.

    This makes the command safe to rerun after a partial or completed backfill.
    """
    filename = Path(image_name).name.lower()

    return (
        filename.endswith(".webp")
        and filename.startswith(GENERATED_PREFIXES)
    )


class Command(BaseCommand):
    help = (
        "Convert existing CategoryImage files to resized WebP files. "
        "Original storage objects are retained for rollback."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help=(
                "Process images in memory and report the expected result "
                "without uploading files or updating the database."
            ),
        )

        parser.add_argument(
            "--ids",
            nargs="+",
            type=int,
            help=(
                "Only process the specified CategoryImage database IDs. "
                "Useful for testing one image before a full production run."
            ),
        )

        parser.add_argument(
            "--force",
            action="store_true",
            help=(
                "Reprocess images previously generated by this optimiser. "
                "Normally generated WebP files are skipped."
            ),
        )

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        selected_ids = options.get("ids")
        force = options["force"]

        queryset = CategoryImage.objects.select_related(
            "category"
        ).order_by("id")

        if selected_ids:
            queryset = queryset.filter(id__in=selected_ids)

        total = queryset.count()
        processed = 0
        skipped = 0
        failed = 0

        if dry_run:
            self.stdout.write(
                self.style.WARNING(
                    "DRY RUN: no files or database records will be changed."
                )
            )

        if selected_ids:
            self.stdout.write(
                f"Selected CategoryImage IDs: {selected_ids}"
            )

        self.stdout.write(f"Found {total} category image record(s).")

        for category_image in queryset.iterator():
            field_file = category_image.image
            image_name = field_file.name if field_file else ""

            label = (
                f"ID {category_image.id} "
                f"[{category_image.category.name}] "
                f"{category_image.name}"
            )

            if not image_name:
                skipped += 1
                self.stdout.write(
                    self.style.WARNING(
                        f"Skipped {label}: no image is assigned."
                    )
                )
                continue

            if image_name == DEFAULT_CATEGORY_IMAGE:
                skipped += 1
                self.stdout.write(
                    self.style.WARNING(
                        f"Skipped {label}: default placeholder image."
                    )
                )
                continue

            if is_generated_image(image_name) and not force:
                skipped += 1
                self.stdout.write(
                    f"Skipped {label}: already optimised "
                    f"({image_name})."
                )
                continue

            try:
                original_size = field_file.size
                original_name = image_name

                field_file.open("rb")

                try:
                    result = optimise_uploaded_image(
                        field_file,
                        **category_image._optimisation_settings(),
                    )
                finally:
                    field_file.close()

                reduction = (
                    100 - (
                        result.byte_size / original_size * 100
                    )
                    if original_size
                    else 0
                )

                if dry_run:
                    processed += 1

                    self.stdout.write(
                        self.style.SUCCESS(
                            f"Would optimise {label}: "
                            f"{original_name} "
                            f"({format_bytes(original_size)}) -> "
                            f"{result.content.name} "
                            f"({result.width}x{result.height}, "
                            f"{format_bytes(result.byte_size)}, "
                            f"{reduction:.1f}% smaller)"
                        )
                    )
                    continue

                # FieldFile.save() routes the processed ContentFile through
                # the currently configured storage backend. In production
                # this is DigitalOcean Spaces.
                field_file.save(
                    result.content.name,
                    result.content,
                    save=False,
                )

                # The FieldFile is now committed, so CategoryImage.save()
                # will not process it for a second time.
                category_image.save(update_fields=["image"])

                processed += 1

                self.stdout.write(
                    self.style.SUCCESS(
                        f"Optimised {label}: "
                        f"{original_name} "
                        f"({format_bytes(original_size)}) -> "
                        f"{category_image.image.name} "
                        f"({result.width}x{result.height}, "
                        f"{format_bytes(result.byte_size)}, "
                        f"{reduction:.1f}% smaller)"
                    )
                )

            except Exception as error:
                failed += 1

                self.stderr.write(
                    self.style.ERROR(
                        f"Failed {label} ({image_name}): "
                        f"{error.__class__.__name__}: {error}"
                    )
                )

        action = "would be processed" if dry_run else "processed"

        self.stdout.write("")
        self.stdout.write(
            f"Summary: {processed} {action}, "
            f"{skipped} skipped, {failed} failed."
        )

        if failed:
            raise CommandError(
                f"{failed} category image(s) could not be processed."
            )