# Generated by Django 4.1.13 on 2026-09-29 21:44

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_homeslide"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productoption",
            old_name="price",
            new_name="price_adjustment",
        ),
        migrations.AlterField(
            model_name="productoption",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productoption",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="help_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name="productoption",
            options={"ordering": ("display_order", "id")},
        ),
        migrations.AlterModelOptions(
            name="productoptiongroup",
            options={"ordering": ("display_order", "id")},
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.CheckConstraint(
                check=models.Q(("price_adjustment__gte", Decimal("0.00"))),
                name="productoption_price_adjustment_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("group__isnull", False)),
                fields=("group",),
                name="unique_default_option_per_group",
            ),
        ),
    ]
