# Generated by Django 4.1.13 on 2026-09-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_product_option_configuration"),
        ("cart", "0002_cartitem_constraints_and_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="configuration_signature",
            field=models.CharField(default="", editable=False, max_length=512),
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_product_per_cart",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "configuration_signature"),
                name="unique_product_configuration_per_cart",
            ),
        ),
        migrations.CreateModel(
            name="CartItemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="cart.cartitem",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_item_selections",
                        to="store.productoptiongroup",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_item_selections",
                        to="store.productoption",
                    ),
                ),
            ],
            options={
                "ordering": ("group_id", "option_id", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="cartitemoption",
            constraint=models.UniqueConstraint(
                fields=("cart_item", "group"),
                name="unique_group_per_cart_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitemoption",
            constraint=models.UniqueConstraint(
                fields=("cart_item", "option"),
                name="unique_option_per_cart_item",
            ),
        ),
    ]
