# Generated by Django 4.1.13 on 2026-10-04 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_item_option_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='guest_session',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='cart.guestsession'),
        ),
    ]
