# Generated by Django 4.1.13 on 2026-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_guest_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartRateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('subject_key', models.CharField(max_length=64)),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_start', models.DateTimeField()),
                ('count', models.BigIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cartratelimitcounter',
            constraint=models.UniqueConstraint(fields=('scope', 'subject_key', 'window_seconds', 'window_start'), name='cart_rate_limit_window_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cartratelimitcounter',
            constraint=models.CheckConstraint(check=models.Q(('scope__in', ('issuance', 'failed_access', 'authenticated_cart'))), name='cart_rate_limit_counter_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='cartratelimitcounter',
            constraint=models.CheckConstraint(check=models.Q(('count__gte', 0)), name='cart_rate_limit_counter_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='cartratelimitcounter',
            constraint=models.CheckConstraint(check=models.Q(('window_seconds__gte', 1), ('window_seconds__lte', 86400)), name='cart_rate_limit_counter_window_range'),
        ),
        migrations.AddConstraint(
            model_name='cartratelimitcounter',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('window_start'))), name='cart_rate_limit_counter_expiry_after_start'),
        ),
    ]
