# Generated by Django 4.1.13 on 2026-10-07 23:08

"""Replace the scope check with issuance, failed_access, authenticated_cart, csrf and reset.

Reversing this migration restores the three-scope check. That reverse is not
safe while csrf or reset rows exist. This migration does not delete rows.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rate_limit_counter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartratelimitcounter',
            name='cart_rate_limit_counter_scope_valid',
        ),
        migrations.AddConstraint(
            model_name='cartratelimitcounter',
            constraint=models.CheckConstraint(check=models.Q(('scope__in', ('issuance', 'failed_access', 'authenticated_cart', 'csrf', 'reset'))), name='cart_rate_limit_counter_scope_valid'),
        ),
    ]
