# Generated by Django 4.1.13 on 2026-10-04 09:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_cart_item_option_configuration'),
        ('store', '0026_product_option_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=40)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('vehicle_wheelbase', models.CharField(max_length=50)),
                ('vehicle_registration', models.CharField(blank=True, max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('full_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_on_completion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fulfilment_method', models.CharField(default='workshop_fitting', max_length=32)),
                ('fitting_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_treatment', models.CharField(default='not_vat_registered', max_length=32)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_terms', models.CharField(default='one_third_deposit_balance_on_completion', max_length=80)),
                ('payment_terms_text', models.CharField(default='One-third deposit. Balance due on completion of the work and fitting.', max_length=255)),
                ('payment_status', models.CharField(default='pending_deposit', max_length=32)),
                ('job_status', models.CharField(default='new', max_length=32)),
                ('internal_notes', models.TextField(blank=True)),
                ('source_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_orders', to='cart.cart')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('original_product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_slug', models.SlugField()),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('configuration_signature', models.CharField(max_length=512)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('base_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('options_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('configured_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_snapshots', to='store.product')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('original_group_id', models.PositiveIntegerField()),
                ('original_option_id', models.PositiveIntegerField()),
                ('group_name', models.CharField(max_length=100)),
                ('option_name', models.CharField(max_length=100)),
                ('option_sku', models.CharField(blank=True, max_length=50)),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_option_snapshots', to='store.productoptiongroup')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_option_snapshots', to='store.productoption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='orders.orderitem')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='orderitemoption',
            constraint=models.UniqueConstraint(fields=('order_item', 'position'), name='unique_option_position_per_order_item'),
        ),
        migrations.AddConstraint(
            model_name='orderitemoption',
            constraint=models.UniqueConstraint(fields=('order_item', 'original_group_id'), name='unique_group_per_order_item'),
        ),
        migrations.AddConstraint(
            model_name='orderitemoption',
            constraint=models.UniqueConstraint(fields=('order_item', 'original_option_id'), name='unique_option_per_order_item'),
        ),
        migrations.AddConstraint(
            model_name='orderitemoption',
            constraint=models.CheckConstraint(check=models.Q(('price_adjustment__gte', 0)), name='orderitemoption_price_adjustment_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'position'), name='unique_position_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='orderitem_quantity_1_to_999'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('base_unit_price__gte', 0), ('options_total__gte', 0), ('configured_unit_price__gte', 0), ('line_total__gte', 0)), name='orderitem_money_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('configured_unit_price', django.db.models.expressions.CombinedExpression(models.F('base_unit_price'), '+', models.F('options_total')))), name='orderitem_configured_unit_matches_parts'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('configured_unit_price'), '*', models.F('quantity')))), name='orderitem_line_total_matches_quantity'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('full_total__gt', 0)), name='order_full_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('deposit_required__gte', 0), ('balance_on_completion__gte', 0), ('amount_paid__gte', 0), ('fitting_charge__gte', 0), ('tax_amount__gte', 0)), name='order_money_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__lte', models.F('full_total'))), name='order_amount_paid_lte_full_total'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('deposit_required', django.db.models.expressions.CombinedExpression(models.F('full_total'), '-', models.F('balance_on_completion')))), name='order_deposit_plus_balance_equals_total'),
        ),
    ]
