# Generated by Django 4.1.13 on 2026-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finalised',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
