# Generated by Django 4.1.13 on 2026-10-04 11:56

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.math
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_finalised'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_deposit_plus_balance_equals_total',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=django.db.models.lookups.Exact(django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('full_total'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()), django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('deposit_required'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()), '+', django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('balance_on_completion'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()))), name='order_deposit_plus_balance_equals_total'),
        ),
    ]
