# Generated by Django 4.1.13 on 2026-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_deposit_balance_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='configuration_signature',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
