# Generated by Django 4.1.13 on 2026-10-04 13:21

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.math
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_configuration_signature_blank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_configured_unit_matches_parts',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orderitem_line_total_matches_quantity',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=django.db.models.lookups.Exact(django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('configured_unit_price'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()), django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('base_unit_price'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()), '+', django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('options_total'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()))), name='orderitem_configured_unit_matches_parts'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=django.db.models.lookups.Exact(django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('line_total'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()), django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('configured_unit_price'), '*', models.Value(100)), precision=0), output_field=models.BigIntegerField()), '*', models.F('quantity'))), name='orderitem_line_total_matches_quantity'),
        ),
    ]
